<a href="https://colab.research.google.com/github/19PA1A0496/python-basics/blob/master/numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
a=np.array([1,2,3])
print(a)


[1 2 3]


In [8]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [0]:
import numpy as np
a=np.arange(15)
print(a)

In [15]:
import numpy as np
v=np.arange(1,20,2)
print(v)


[ 1  3  5  7  9 11 13 15 17 19]


In [19]:
import numpy as np
a=np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [20]:
import numpy as np
a=np.arange(20).reshape(10,2)
print(a)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [30]:
import numpy as np
a=np.arange(6).reshape(3,2)
print(a)
b=a.shape
print(b)
c=a.ndim
print(c)
d=a.dtype
print(d)
e=a.itemsize
print(e)

[[0 1]
 [2 3]
 [4 5]]
(3, 2)
2
int64
8


In [31]:
import numpy as np
a=np.arange(4).reshape(2,2)
b=a.shape
c=a.ndim
d=a.dtype
s=a.itemsize
print(a)
print(b)
print(c)
print(d)
print(s)

[[0 1]
 [2 3]]
(2, 2)
2
int64
8


In [34]:
import numpy as np
a=np.arange(20).reshape(10,2)
print(a)
b=a.itemsize
print(b)
c=a.size
print(c)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]
8
20


In [39]:
import numpy as np
a=np.arange(20).reshape(5,4)
b=a.shape
c=a.dtype
d=a.size
e=a.itemsize
f=a.ndim
print(a)
print(b)
print(c)
print(d)
print(e)
print(f)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
(5, 4)
int64
20
8
2


In [41]:
import numpy as np
a=np.arange(4).reshape(2,2)
print(a)
type(a)

[[0 1]
 [2 3]]


numpy.ndarray

In [50]:
import numpy as np
a=np.eye(2)
b=np.zeros((6,6))
c=np.ones((2,3),dtype=np.int32)
print(a)
print(b)
print(c)

[[1. 0.]
 [0. 1.]]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[1 1 1]
 [1 1 1]]


In [64]:
import numpy as np
a=np.ones((2,2))
b=np.zeros((2,2))
c=np.eye(4)
d=np.full((2,2),1)
e=np.random.random((5))
f=np.empty((2,2))
print(a)
print(b)
print(c)
print(d)
print(e)
print(f)


[[1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1 1]
 [1 1]]
[0.76155774 0.65823545 0.63929654 0.40807997 0.571143  ]
[[0.81706094 0.4325885 ]
 [0.48604669 0.67619664]]


In [59]:
import numpy as np
a=np.array([20,30,40,50])
b=np.arange(4)
print(a)
print(b)
c=a-b
print(c)
d=b**2
print(d)


[20 30 40 50]
[0 1 2 3]
[20 29 38 47]
[0 1 4 9]


In [61]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[0,1],[3,2]])
print(a)
print(b)
print(a*b)
print(a-b)
print(a+b)
print(a@b)
print(a.dot(b))
print(np.dot(a,b))

[[1 2]
 [3 4]]
[[0 1]
 [3 2]]
[[0 2]
 [9 8]]
[[1 1]
 [0 2]]
[[1 3]
 [6 6]]
[[ 6  5]
 [12 11]]
[[ 6  5]
 [12 11]]
[[ 6  5]
 [12 11]]


In [63]:
import numpy as np
a=np.arange(12).reshape(4,3)
print(a)
print(a.sum())
print(a.sum(axis=0))
print(a.sum(axis=1))
print(a.cumsum(axis=1))
print(a.cumsum(axis=0))
print(a.max(axis=0))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
66
[18 22 26]
[ 3 12 21 30]
[[ 0  1  3]
 [ 3  7 12]
 [ 6 13 21]
 [ 9 19 30]]
[[ 0  1  2]
 [ 3  5  7]
 [ 9 12 15]
 [18 22 26]]
[ 9 10 11]


In [67]:
import numpy as np
a=np.arange(10)**3
print(a)
print(a[1:4])
print(a[2:6])

[  0   1   8  27  64 125 216 343 512 729]
[ 1  8 27]
[  8  27  64 125]


In [69]:
import numpy as np
a=np.array([[11,12,13],[14,15,16],[2,2,2]])
b=np.array([[1,2,3]])
print(a)
print(b)
c=a+b
k=a-b
n=a*b
print(k)
print(n)
print(c)

[[11 12 13]
 [14 15 16]
 [ 2  2  2]]
[[1 2 3]]
[[10 10 10]
 [13 13 13]
 [ 1  0 -1]]
[[11 24 39]
 [14 30 48]
 [ 2  4  6]]
[[12 14 16]
 [15 17 19]
 [ 3  4  5]]


In [70]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a)
c=np.hspilt(a,3)
d=np.vspilt(a,3)
print(c)
print(d)

[[1 2 3]
 [4 5 6]]


AttributeError: ignored